const CAT_LIST_REQUEST = 'CAT_LIST_REQUEST';
const CAT_LIST_SUCCESS = 'CAT_LIST_SUCCESS';
const CAT_LIST_FAILURE = 'CAT_LIST_FAILURE';
const CAT_CREATE_FAILURE = 'CAT_CREATE_FAILURE';
const CAT_CREATE_REQUEST = 'CAT_CREATE_REQUEST';
const CAT_CREATE_SUCCESS = 'CAT_CREATE_SUCCESS';
const CAT_DELETE_FAILURE = 'CAT_DELETE_FAILURE';
const CAT_DELETE_REQUEST = 'CAT_DELETE_REQUEST';
const CAT_DELETE_SUCCESS = 'CAT_DELETE_SUCCESS';
const CAT_EDIT_FAILURE = 'CAT_EDIT_FAILURE';
const CAT_EDIT_REQUEST = 'CAT_EDIT_REQUEST';
const CAT_EDIT_SUCCESS = 'CAT_EDIT_SUCCESS';

const types = {
    CAT_LIST_REQUEST,
    CAT_LIST_SUCCESS,
    CAT_LIST_FAILURE,
    CAT_CREATE_REQUEST,
    CAT_CREATE_SUCCESS,
    CAT_CREATE_FAILURE,
    CAT_DELETE_REQUEST,
    CAT_DELETE_SUCCESS,
    CAT_DELETE_FAILURE,
    CAT_EDIT_REQUEST,
    CAT_EDIT_SUCCESS,
    CAT_EDIT_FAILURE,
}

export default types;