const BREED_LIST_REQUEST = 'BREED_LIST_REQUEST';
const BREED_LIST_SUCCESS = 'BREED_LIST_SUCCESS';
const BREED_LIST_FAILURE = 'BREED_LIST_FAILURE';
const BREED_CREATE_FAILURE = 'BREED_CREATE_FAILURE';
const BREED_CREATE_REQUEST = 'BREED_CREATE_REQUEST';
const BREED_CREATE_SUCCESS = 'BREED_CREATE_SUCCESS';
const BREED_EDIT_FAILURE = 'BREED_EDIT_FAILURE';
const BREED_EDIT_REQUEST = 'BREED_EDIT_REQUEST';
const BREED_EDIT_SUCCESS = 'BREED_EDIT_SUCCESS';
const BREED_DELETE_FAILURE = 'BREED_DELETE_FAILURE';
const BREED_DELETE_REQUEST = 'BREED_DELETE_REQUEST';
const BREED_DELETE_SUCCESS = 'BREED_DELETE_SUCCESS';


const types = {
    BREED_LIST_REQUEST,
    BREED_LIST_SUCCESS,
    BREED_LIST_FAILURE,
    BREED_CREATE_REQUEST,
    BREED_CREATE_SUCCESS,
    BREED_CREATE_FAILURE,
    BREED_DELETE_REQUEST,
    BREED_DELETE_SUCCESS,
    BREED_DELETE_FAILURE,
    BREED_EDIT_REQUEST,
    BREED_EDIT_SUCCESS,
    BREED_EDIT_FAILURE
}

export default types;